### PR TITLE
update device detection for new firmware

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
I noted that I do need to start the bitcoin app for the dongle to be found, which is new, but all right.

However I have the following error:

    $ RUST_BACKTRACE=1 result/bin/icboc test.wallet init-testnet acc 5
    Successfully found dongle NanoS
    Firmware version 1.3.17
    thread 'main' panicked at 'Parsing account as number: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:1165:5
    stack backtrace:
       0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
       1: core::fmt::write
       2: std::io::Write::write_fmt
       3: std::panicking::default_hook::{{closure}}
       4: std::panicking::default_hook
       5: std::panicking::rust_panic_with_hook
       6: std::panicking::continue_panic_fmt
       7: rust_begin_unwind
       8: core::panicking::panic_fmt
       9: core::result::unwrap_failed
      10: icboc::main
      11: std::rt::lang_start::{{closure}}
      12: std::panicking::try::do_call
      13: __rust_maybe_catch_pani, 
      14: std::rt::lang_start_internal
      15: main
      16: __libc_start_main
      17: _start
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

I'm running the bitcoin app version 1.3.17;  SE version 1.6.0.

**Comment by roconnor-blockstream** [comment]
I am able to connect and initialize a testnet account with firmware version 1.6.0 and bitcoin app version 1.3.17, whereas I am unable to find the dongle with version 15cdd488954dbf1148f970d7ed743a777c9dcbd4 from https://github.com/apoelstra/icebox/pull/9.

**Comment by apoelstra** [comment]
I'm able to make this work with 1.5.5.

I understand from talking to you off-channel that there are other firmware versions that don't work, apparently because the format of the "get version" message changes between versions. I think we shuold defer those to future PRs.

**Comment by roconnor-blockstream** [comment]
I am no longer as sure that other firmware doesn't work.  It seems that you need to run the BTC app or you get a dongle not found error, and I never installed the BTC app when I was briefly running firmware 1.4.4.  Anyhow I don't see too much point in supporting anything much older than the latest firmware.

**Pull request merged**
