### PR TITLE
Update codebase to modern standards

### PR DESCRIPTION
**Pull request by apoelstra**
Basically, fix all the clippy lints.

### CODE REVIEW

**Comment by roconnor** [comment]
Update --help information in commands/mod.rs if it is really the case that info doesn't take any options.

**Comment by apoelstra** [comment]
@roconnor done

**Comment by roconnor** [comment]
LGTMFWIW

**Comment by roconnor** [comment]
I know I said LGTM, but I think the `info` command is actually broken.

**Comment by apoelstra** [comment]
Is it? I tried it and it worked.

**Comment by roconnor** [comment]
I get

    $ icboc3d main3d.wallet info
    Found dongle.
        …
    Error: deserializing options for info
    
    Caused by:
        invalid type: map, expected unit at line 1 column 0

before even unlocking the wallet.

**Comment by apoelstra** [comment]
@roconnor are you on the latest version of this PR? I got this too but I force-pushed to fix it.

**Comment by roconnor** [comment]
I'm pretty sure I'm on c3b429be0f1c89cf327fdade371864f8da258722

**Comment by apoelstra** [comment]
Oops, crap, I think I re-tested on the wrong commit.

Will fix in a followup PR.

**Comment by apoelstra** [comment]
https://github.com/apoelstra/icboc/pull/23

**Pull request merged**
